# Cloudflare Warp configuration for FanzDash
name = "fanzdash"
main = "server/warp-worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
NODE_ENV = "production"
PORT = "8080"

[env.preview.vars]
NODE_ENV = "development"
PORT = "8080"

# KV Namespaces for caching and session storage
[[kv_namespaces]]
binding = "CACHE"
id = "fanzdash-cache"
preview_id = "fanzdash-cache-preview"

[[kv_namespaces]]
binding = "SESSIONS"
id = "fanzdash-sessions"
preview_id = "fanzdash-sessions-preview"

# Durable Objects for real-time features
[[durable_objects.bindings]]
name = "WEBSOCKET_SESSIONS"
class_name = "WebSocketSession"

[[durable_objects.bindings]]
name = "LIVE_STREAMS"
class_name = "LiveStreamSession"

[[durable_objects.bindings]]
name = "CHAT_ROOMS"
class_name = "ChatRoomSession"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketSession", "LiveStreamSession", "ChatRoomSession"]

# R2 bucket for file storage
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "fanzdash-media"

[[r2_buckets]]
binding = "LOGS_BUCKET"
bucket_name = "fanzdash-logs"

# Analytics Engine for metrics
[[analytics_engine_datasets]]
binding = "ANALYTICS"

# Queue for background tasks
[[queues]]
binding = "BACKGROUND_TASKS"
queue = "fanzdash-tasks"

[[queues.consumers]]
queue = "fanzdash-tasks"
max_batch_size = 10
max_batch_timeout = 5

# Worker routes
[triggers]
crons = ["0 */6 * * *"]  # Sync every 6 hours

# Development configuration
[dev]
port = 8787
local_protocol = "https"
upstream_protocol = "https"

# Security headers
[security]
csrf_protection = true
content_security_policy = true

# Limits
[limits]
cpu_ms = 30000
memory_mb = 128