global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # FANZ Application Metrics
  - job_name: 'fanz-app'
    static_configs:
      - targets: ['app:3000']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # PostgreSQL Metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: /metrics
    scrape_interval: 30s

  # Redis Metrics  
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s

  # NGINX Metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /nginx_status
    scrape_interval: 15s

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # AI Service Metrics
  - job_name: 'ai-service'
    static_configs:
      - targets: ['ai-service:8501']
    metrics_path: /monitoring/prometheus/metrics
    scrape_interval: 30s

  # WebRTC Signaling Server
  - job_name: 'webrtc-signaling'
    static_configs:
      - targets: ['webrtc-signaling:8080']
    metrics_path: /metrics
    scrape_interval: 30s