name: 🔐 FANZ Secret Scanning

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM

jobs:
  secret-scan:
    name: Secret Detection Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install Gitleaks
      run: |
        wget -qO- https://github.com/zricethezav/gitleaks/releases/download/v8.18.0/gitleaks_8.18.0_linux_x64.tar.gz | tar xzf -
        sudo mv gitleaks /usr/local/bin/
    
    - name: Run Gitleaks Scan
      run: |
        gitleaks detect --config .gitleaks.toml --report-format sarif --report-path gitleaks.sarif --verbose
    
    - name: Upload Gitleaks SARIF
      if: always()
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: gitleaks.sarif
        category: gitleaks
    
    - name: Adult Platform Secret Check
      run: |
        echo "🔍 Running FANZ-specific secret validation..."
        # Custom validation for adult content platform secrets
        if gitleaks detect --config .gitleaks.toml --no-git | grep -E "(ccbill|paxum|segpay|epoch)"; then
          echo "🚨 CRITICAL: Payment processor secrets detected!"
          exit 1
        fi
        echo "✅ No critical payment secrets found"
    
    - name: Notify Security Team
      if: failure()
      run: |
        echo "🚨 Secret scan failed - notifying security team"
        # Integration with FanzDash notification system would go here
